<nav class="navbar navbar-expand-lg main-navbar {{ $preferences['navbar'] === 'sticky' ? 'sticky' : '' }}">
    <div class="form-inline mr-auto"><ul class="navbar-nav mr-3">
        <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg collapse-btn" aria-label="Buka atau tutup menu"><i data-feather="align-justify"></i></a></li>
        <li><a href="#" class="nav-link nav-link-lg fullscreen-btn" aria-label="Layar penuh"><i data-feather="maximize"></i></a></li>
    </ul></div>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg" aria-label="Notifikasi"><i data-feather="bell"></i><span class="badge badge-primary badge-pill">{{ $unreadNotificationCount ?? 0 }}</span></a><div class="dropdown-menu dropdown-list dropdown-menu-right"><div class="dropdown-header">Notifikasi <div class="float-right"><a href="{{ route('notifications.index') }}">Lihat semua</a></div></div><div class="dropdown-list-content dropdown-list-icons">@forelse(($navbarNotifications ?? collect()) as $notification)<a href="{{ route('notifications.read', $notification) }}" class="dropdown-item"><div class="dropdown-item-icon bg-primary text-white"><i data-feather="bell"></i></div><div class="dropdown-item-desc"><strong>{{ $notification->title }}</strong><div>{{ $notification->message }}</div><small>{{ $notification->created_at->diffForHumans() }}</small></div></a>@empty<div class="dropdown-item text-center text-muted">Belum ada notifikasi.</div>@endforelse</div></div></li>
        <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user"><img alt="Foto profil default" src="{{ asset('img/user.png') }}" class="user-img-radious-style"><span class="d-none d-sm-inline-block">{{ auth()->user()->name }}</span></a><div class="dropdown-menu dropdown-menu-right"><div class="dropdown-title">Masuk sebagai {{ auth()->user()->role->value }}</div><a href="{{ route('profile') }}" class="dropdown-item has-icon"><i data-feather="user"></i> Profil</a><div class="dropdown-divider"></div><form method="POST" action="{{ route('logout') }}">@csrf<button type="submit" class="dropdown-item has-icon text-danger"><i data-feather="log-out"></i> Keluar</button></form></div></li>
    </ul>
</nav>
