@extends('layouts.app')

@section('title', 'Metode Pembayaran')
@section('page-title', 'Metode Pembayaran')
@section('breadcrumb', 'Metode Pembayaran')

@section('content')
<div class="card"><div class="card-header"><h4>Daftar Metode Pembayaran</h4><div class="card-header-action"><button class="btn btn-primary" data-toggle="modal" data-target="#payment-method-create-modal"><i class="fas fa-plus"></i> Tambah Metode</button></div></div><div class="card-body"><div class="table-responsive"><table id="payment-methods-table" class="table table-striped"><thead><tr><th>Jenis</th><th>Nama</th><th>Nomor Rekening/Akun</th><th>Atas Nama</th><th>Status</th><th>Penggunaan</th><th>Aksi</th></tr></thead><tbody>@forelse ($paymentMethods as $paymentMethod)<tr><td>{{ $paymentMethod->type->value === 'ewallet' ? 'E-Wallet' : 'Transfer' }}</td><td>{{ $paymentMethod->name }}</td><td>{{ $paymentMethod->account_number }}</td><td>{{ $paymentMethod->account_name }}</td><td><span class="badge badge-{{ $paymentMethod->is_active ? 'success' : 'secondary' }}">{{ $paymentMethod->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td>{{ $paymentMethod->payments_count }} pembayaran</td><td class="text-nowrap"><button type="button" class="btn btn-sm btn-info js-edit-payment-method" data-toggle="modal" data-target="#payment-method-edit-modal" data-id="{{ $paymentMethod->id }}" data-type="{{ $paymentMethod->type->value }}" data-name="{{ $paymentMethod->name }}" data-number="{{ $paymentMethod->account_number }}" data-account-name="{{ $paymentMethod->account_name }}" data-active="{{ $paymentMethod->is_active ? 1 : 0 }}"><i class="fas fa-edit"></i> Edit</button> @if ($paymentMethod->payments_count === 0)<button type="button" class="btn btn-sm btn-danger js-delete-payment-method" data-toggle="modal" data-target="#payment-method-delete-modal" data-id="{{ $paymentMethod->id }}" data-name="{{ $paymentMethod->name }}"><i class="fas fa-trash"></i></button>@endif</td></tr>@empty<tr><td colspan="7" class="text-center text-muted">Belum ada metode pembayaran.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="modal fade" id="payment-method-create-modal" tabindex="-1" role="dialog" aria-labelledby="payment-method-create-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form method="POST" action="{{ route('admin.payment-methods.store') }}"><div class="modal-header"><h5 id="payment-method-create-title" class="modal-title">Tambah Metode Pembayaran</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><div class="modal-body">@csrf<input type="hidden" name="form" value="create"><div class="form-group"><label for="payment-method-create-type">Jenis</label><select id="payment-method-create-type" name="type" class="form-control" required><option value="transfer">Transfer</option><option value="ewallet">E-Wallet</option></select></div><div class="form-group"><label for="payment-method-create-name">Nama</label><input id="payment-method-create-name" name="name" class="form-control" required></div><div class="form-group"><label for="payment-method-create-number">Nomor rekening/akun</label><input id="payment-method-create-number" name="account_number" class="form-control" required></div><div class="form-group"><label for="payment-method-create-account-name">Atas nama</label><input id="payment-method-create-account-name" name="account_name" class="form-control" required></div><input type="hidden" name="is_active" value="1"></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div></div>
<div class="modal fade" id="payment-method-edit-modal" tabindex="-1" role="dialog" aria-labelledby="payment-method-edit-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form id="payment-method-edit-form" method="POST"><div class="modal-header"><h5 id="payment-method-edit-title" class="modal-title">Edit Metode Pembayaran</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><div class="modal-body">@csrf @method('PUT')<input type="hidden" name="form" value="edit"><div class="form-group"><label for="payment-method-edit-type">Jenis</label><select id="payment-method-edit-type" name="type" class="form-control" required><option value="transfer">Transfer</option><option value="ewallet">E-Wallet</option></select></div><div class="form-group"><label for="payment-method-edit-name">Nama</label><input id="payment-method-edit-name" name="name" class="form-control" required></div><div class="form-group"><label for="payment-method-edit-number">Nomor rekening/akun</label><input id="payment-method-edit-number" name="account_number" class="form-control" required></div><div class="form-group"><label for="payment-method-edit-account-name">Atas nama</label><input id="payment-method-edit-account-name" name="account_name" class="form-control" required></div><input type="hidden" name="is_active" value="0"><div class="custom-control custom-checkbox"><input id="payment-method-edit-active" type="checkbox" class="custom-control-input"><label class="custom-control-label" for="payment-method-edit-active">Aktif</label></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary">Simpan Perubahan</button></div></form></div></div></div>
<div class="modal fade" id="payment-method-delete-modal" tabindex="-1" role="dialog" aria-labelledby="payment-method-delete-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form id="payment-method-delete-form" method="POST"><div class="modal-header"><h5 id="payment-method-delete-title" class="modal-title">Hapus Metode Pembayaran</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><div class="modal-body">@csrf @method('DELETE')<p>Hapus metode <strong id="payment-method-delete-name"></strong>?</p></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-danger">Hapus</button></div></form></div></div></div>
@push('styles')<link rel="stylesheet" href="{{ asset('bundles/datatables/datatables.min.css') }}">@endpush
@push('plugin-scripts')<script src="{{ asset('bundles/datatables/datatables.min.js') }}"></script>@endpush
@push('scripts')<script>$(function(){ $('#payment-methods-table').DataTable({pageLength:10,ordering:true,responsive:true}); $('.js-edit-payment-method').on('click',function(){var b=$(this);$('#payment-method-edit-form').attr('action','{{ url('/admin/payment-methods') }}/'+b.data('id'));$('#payment-method-edit-type').val(b.data('type'));$('#payment-method-edit-name').val(b.data('name'));$('#payment-method-edit-number').val(b.data('number'));$('#payment-method-edit-account-name').val(b.data('account-name'));$('#payment-method-edit-active').prop('checked',String(b.data('active'))==='1').on('change',function(){$('#payment-method-edit-form input[name=is_active]').val(this.checked?'1':'0');}).trigger('change');});$('.js-delete-payment-method').on('click',function(){var b=$(this);$('#payment-method-delete-form').attr('action','{{ url('/admin/payment-methods') }}/'+b.data('id'));$('#payment-method-delete-name').text(b.data('name'));});@if($errors->any() && old('form')==='create')$('#payment-method-create-modal').modal('show');@endif });</script>@endpush
@endsection
