@extends('layouts.app')

@section('title', 'Dashboard Admin')
@section('page-title', 'Dashboard Admin')
@section('breadcrumb', 'Dashboard')

@section('content')
<div class="row"><div class="col-12"><div class="alert alert-light border">Ringkasan periode <strong>{{ $period }}</strong></div></div>@include('dashboard.partials.stat-card', ['label' => 'Total Tagihan', 'value' => $billTotal, 'icon' => 'file-invoice', 'color' => 'primary', 'empty' => $billTotal === 0])@include('dashboard.partials.stat-card', ['label' => 'Lunas', 'value' => $billStatuses['lunas'], 'icon' => 'check-circle', 'color' => 'success', 'empty' => $billStatuses['lunas'] === 0])@include('dashboard.partials.stat-card', ['label' => 'Belum Bayar', 'value' => $billStatuses['belum_bayar'], 'icon' => 'clock', 'color' => 'warning', 'empty' => $billStatuses['belum_bayar'] === 0])@include('dashboard.partials.stat-card', ['label' => 'Terlambat', 'value' => $billStatuses['terlambat'], 'icon' => 'exclamation-triangle', 'color' => 'danger', 'empty' => $billStatuses['terlambat'] === 0])@include('dashboard.partials.stat-card', ['label' => 'Menunggu Verifikasi', 'value' => $billStatuses['menunggu_verifikasi'], 'icon' => 'hourglass-half', 'color' => 'info', 'empty' => $billStatuses['menunggu_verifikasi'] === 0])@include('dashboard.partials.stat-card', ['label' => 'Pendapatan Hari Ini', 'value' => format_rupiah($revenueToday), 'icon' => 'calendar-day', 'color' => 'success', 'empty' => (float) $revenueToday === 0.0])@include('dashboard.partials.stat-card', ['label' => 'Pendapatan Bulan Ini', 'value' => format_rupiah($revenueMonth), 'icon' => 'money-bill-wave', 'color' => 'primary', 'empty' => (float) $revenueMonth === 0.0])@include('dashboard.partials.stat-card', ['label' => 'Payment Pending', 'value' => $pendingPayments, 'icon' => 'inbox', 'color' => 'warning', 'empty' => $pendingPayments === 0])@include('dashboard.partials.stat-card', ['label' => 'Upgrade Pending', 'value' => $pendingUpgrades, 'icon' => 'level-up-alt', 'color' => 'info', 'empty' => $pendingUpgrades === 0])</div>
<div class="row"><div class="col-12 col-lg-6"><div class="card"><div class="card-header"><h4>Payment Pending</h4><div class="card-header-action"><a href="{{ route('admin.payments.index', ['status' => 'pending']) }}">Lihat semua</a></div></div><div class="card-body"><p>{{ $pendingPayments }} pembayaran menunggu verifikasi.</p>@if($pendingPayments === 0)<div class="empty-state py-3"><div class="empty-state-icon"><i class="fas fa-check"></i></div><p class="lead">Tidak ada payment pending.</p></div>@else<a href="{{ route('admin.payments.index', ['status' => 'pending']) }}" class="btn btn-sm btn-primary">Buka verifikasi</a>@endif</div></div></div><div class="col-12 col-lg-6"><div class="card"><div class="card-header"><h4>Upgrade Pending</h4><div class="card-header-action"><a href="{{ route('admin.upgrades.index', ['status' => 'pending']) }}">Lihat semua</a></div></div><div class="card-body"><p>{{ $pendingUpgrades }} pengajuan menunggu keputusan.</p>@if($pendingUpgrades === 0)<div class="empty-state py-3"><div class="empty-state-icon"><i class="fas fa-check"></i></div><p class="lead">Tidak ada upgrade pending.</p></div>@else<a href="{{ route('admin.upgrades.index', ['status' => 'pending']) }}" class="btn btn-sm btn-primary">Buka pengajuan</a>@endif</div></div></div></div>
@include('dashboard.partials.transactions', ['transactions' => $transactions])
@endsection
