@extends('layouts.app')

@section('title', 'Dashboard Customer')
@section('page-title', 'Dashboard Customer')
@section('breadcrumb', 'Dashboard')

@section('content')
@if($overdueBills->isNotEmpty())<div class="alert alert-danger"><i class="fas fa-exclamation-triangle"></i> Anda memiliki {{ $overdueBills->count() }} tagihan terlambat. Silakan lakukan pembayaran atau hubungi admin.</div>@endif
<div class="row"><div class="col-12 col-lg-7"><div class="card"><div class="card-header"><h4>Tagihan Periode Berjalan</h4><div class="card-header-action"><a href="{{ route('customer.bills.index') }}">Lihat semua</a></div></div><div class="card-body">@if($currentBill)<dl class="row"><dt class="col-5">Nomor</dt><dd class="col-7">{{ $currentBill->bill_number }}</dd><dt class="col-5">Layanan</dt><dd class="col-7">{{ $currentBill->service->name }}</dd><dt class="col-5">Jumlah</dt><dd class="col-7 font-weight-bold">{{ format_rupiah($currentBill->amount) }}</dd><dt class="col-5">Jatuh tempo</dt><dd class="col-7">{{ format_tanggal_id($currentBill->due_date) }}</dd><dt class="col-5">Status</dt><dd class="col-7">{{ ucfirst(str_replace('_', ' ', $currentBill->status->value)) }}</dd></dl><a href="{{ route('customer.bills.show', $currentBill) }}" class="btn btn-primary">Detail Tagihan</a>@if(in_array($currentBill->status->value, ['belum_bayar','terlambat'], true)) <a href="{{ route('customer.bills.pay', $currentBill) }}" class="btn btn-success">Bayar Sekarang</a>@endif@else<div class="empty-state py-3"><div class="empty-state-icon"><i class="fas fa-file-invoice"></i></div><p class="lead">Belum ada tagihan periode berjalan.</p></div>@endif</div></div></div><div class="col-12 col-lg-5"><div class="card"><div class="card-header"><h4>Layanan Aktif</h4></div><div class="card-body">@if($activeService)<h5>{{ $activeService->name }}</h5><p>{{ $activeService->speed_mbps }} Mbps · {{ format_rupiah($activeService->price) }} / bulan</p>@if($upgrade && $upgrade->status->value === 'approved')<div class="alert alert-info mb-0">Dijadwalkan ke <strong>{{ $upgrade->toService->name }}</strong> mulai {{ $upgrade->effective_period }}.</div>@elseif($upgrade && $upgrade->status->value === 'pending')<div class="alert alert-warning mb-0">Pengajuan upgrade sedang menunggu keputusan.</div>@else<a href="{{ route('customer.services.index') }}">Kelola layanan</a>@endif@else<div class="empty-state py-3"><div class="empty-state-icon"><i class="fas fa-wifi"></i></div><p class="lead">Data layanan belum tersedia.</p></div>@endif</div></div></div></div>
<div class="row"><div class="col-12 col-lg-6"><div class="card"><div class="card-header"><h4>5 Pembayaran Terakhir</h4><div class="card-header-action"><a href="{{ route('customer.payments.index') }}">Lihat semua</a></div></div><div class="card-body"><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Tanggal</th><th>Tagihan</th><th>Jumlah</th><th>Status</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ format_tanggal_id($payment->paid_date) }}</td><td>{{ $payment->bill->bill_number }}</td><td>{{ format_rupiah($payment->amount) }}</td><td>{{ ucfirst($payment->status->value) }}</td></tr>@empty<tr><td colspan="4" class="text-center text-muted">Belum ada pembayaran.</td></tr>@endforelse</tbody></table></div></div></div></div><div class="col-12 col-lg-6"><div class="card"><div class="card-header"><h4>Notifikasi Terbaru</h4><div class="card-header-action"><a href="{{ route('notifications.index') }}">Lihat semua</a></div></div><div class="card-body">@forelse($notifications as $notification)<a href="{{ route('notifications.read', $notification) }}" class="d-block border-bottom py-2"><strong>{{ $notification->title }}</strong><br><small>{{ $notification->message }}</small></a>@empty<div class="empty-state py-3"><div class="empty-state-icon"><i class="fas fa-bell"></i></div><p class="lead">Belum ada notifikasi.</p></div>@endforelse</div></div></div></div>
@endsection
