@extends('layouts.app')

@section('title', 'Dashboard Supervisor')
@section('page-title', 'Dashboard Supervisor')
@section('breadcrumb', 'Dashboard')

@section('content')
<div class="row"><div class="col-12"><div class="alert alert-light border">Ringkasan periode <strong>{{ $period }}</strong></div></div>@include('dashboard.partials.stat-card', ['label' => 'Total Tagihan', 'value' => $billTotal, 'icon' => 'file-invoice', 'color' => 'primary', 'empty' => $billTotal === 0])@include('dashboard.partials.stat-card', ['label' => 'Lunas', 'value' => $billStatuses['lunas'], 'icon' => 'check-circle', 'color' => 'success', 'empty' => $billStatuses['lunas'] === 0])@include('dashboard.partials.stat-card', ['label' => 'Belum Bayar', 'value' => $billStatuses['belum_bayar'], 'icon' => 'clock', 'color' => 'warning', 'empty' => $billStatuses['belum_bayar'] === 0])@include('dashboard.partials.stat-card', ['label' => 'Terlambat', 'value' => $billStatuses['terlambat'], 'icon' => 'exclamation-triangle', 'color' => 'danger', 'empty' => $billStatuses['terlambat'] === 0])@include('dashboard.partials.stat-card', ['label' => 'Menunggu Verifikasi', 'value' => $billStatuses['menunggu_verifikasi'], 'icon' => 'hourglass-half', 'color' => 'info', 'empty' => $billStatuses['menunggu_verifikasi'] === 0])@include('dashboard.partials.stat-card', ['label' => 'Pendapatan Hari Ini', 'value' => format_rupiah($revenueToday), 'icon' => 'calendar-day', 'color' => 'success', 'empty' => (float) $revenueToday === 0.0])@include('dashboard.partials.stat-card', ['label' => 'Pendapatan Bulan Ini', 'value' => format_rupiah($revenueMonth), 'icon' => 'money-bill-wave', 'color' => 'primary', 'empty' => (float) $revenueMonth === 0.0])</div>
<div class="card"><div class="card-header"><h4>Laporan Menunggu Review</h4><div class="card-header-action"><a href="{{ route('supervisor.reports.index', ['status' => 'dikirim']) }}">Lihat semua</a></div></div><div class="card-body">@forelse($pendingReports as $report)<a class="d-block border-bottom py-2" href="{{ route('supervisor.reports.show', $report) }}">Laporan {{ format_tanggal_id($report->report_date) }} <span class="badge badge-warning float-right">Dikirim</span></a>@empty<div class="empty-state py-3"><div class="empty-state-icon"><i class="fas fa-check"></i></div><p class="lead">Tidak ada laporan menunggu review.</p></div>@endforelse</div></div>
@include('dashboard.partials.transactions', ['transactions' => $transactions])
@endsection
