@extends('layouts.app')

@section('title', 'Layanan')
@section('page-title', 'Layanan')
@section('breadcrumb', 'Layanan')

@section('content')
<div class="card"><div class="card-header"><h4>Daftar Layanan</h4><div class="card-header-action"><button class="btn btn-primary" data-toggle="modal" data-target="#service-create-modal"><i class="fas fa-plus"></i> Tambah Layanan</button></div></div><div class="card-body"><div class="table-responsive"><table id="services-table" class="table table-striped"><thead><tr><th>Nama</th><th>Kecepatan</th><th>Harga</th><th>Status</th><th>Penggunaan</th><th>Aksi</th></tr></thead><tbody>@forelse ($services as $service)<tr><td>{{ $service->name }}<small class="d-block text-muted">{{ $service->description ?: 'Tanpa deskripsi' }}</small></td><td>{{ number_format($service->speed_mbps, 0, ',', '.') }} Mbps</td><td>{{ format_rupiah($service->price) }}</td><td><span class="badge badge-{{ $service->is_active ? 'success' : 'secondary' }}">{{ $service->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td>{{ $service->customers_count }} customer / {{ $service->bills_count }} tagihan</td><td class="text-nowrap"><button type="button" class="btn btn-sm btn-info js-edit-service" data-toggle="modal" data-target="#service-edit-modal" data-id="{{ $service->id }}" data-name="{{ $service->name }}" data-speed="{{ $service->speed_mbps }}" data-price="{{ $service->price }}" data-description="{{ $service->description }}" data-active="{{ $service->is_active ? 1 : 0 }}"><i class="fas fa-edit"></i> Edit</button> @if ($service->customers_count === 0 && $service->bills_count === 0)<button type="button" class="btn btn-sm btn-danger js-delete-service" data-toggle="modal" data-target="#service-delete-modal" data-id="{{ $service->id }}" data-name="{{ $service->name }}"><i class="fas fa-trash"></i></button>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">Belum ada layanan.</td></tr>@endforelse</tbody></table></div></div></div>

<div class="modal fade" id="service-create-modal" tabindex="-1" role="dialog" aria-labelledby="service-create-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form method="POST" action="{{ route('admin.services.store') }}"><div class="modal-header"><h5 id="service-create-title" class="modal-title">Tambah Layanan</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><div class="modal-body">@csrf<input type="hidden" name="form" value="create"><div class="form-group"><label for="service-create-name">Nama layanan</label><input id="service-create-name" name="name" class="form-control" value="{{ old('form') === 'create' ? old('name') : '' }}" required></div><div class="form-group"><label for="service-create-speed">Kecepatan (Mbps)</label><input id="service-create-speed" name="speed_mbps" type="number" min="1" class="form-control" value="{{ old('form') === 'create' ? old('speed_mbps') : '' }}" required></div><div class="form-group"><label for="service-create-price">Harga per bulan</label><input id="service-create-price" name="price" type="number" min="0" step="0.01" class="form-control" value="{{ old('form') === 'create' ? old('price') : '' }}" required></div><div class="form-group"><label for="service-create-description">Deskripsi</label><textarea id="service-create-description" name="description" class="form-control">{{ old('form') === 'create' ? old('description') : '' }}</textarea></div><input type="hidden" name="is_active" value="1"><div class="custom-control custom-checkbox"><input id="service-create-active" type="checkbox" class="custom-control-input" checked disabled><label class="custom-control-label" for="service-create-active">Aktif</label></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary">Simpan</button></div></form></div></div></div>
<div class="modal fade" id="service-edit-modal" tabindex="-1" role="dialog" aria-labelledby="service-edit-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form id="service-edit-form" method="POST" action=""><div class="modal-header"><h5 id="service-edit-title" class="modal-title">Edit Layanan</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><div class="modal-body">@csrf @method('PUT')<input type="hidden" name="form" value="edit"><div class="form-group"><label for="service-edit-name">Nama layanan</label><input id="service-edit-name" name="name" class="form-control" required></div><div class="form-group"><label for="service-edit-speed">Kecepatan (Mbps)</label><input id="service-edit-speed" name="speed_mbps" type="number" min="1" class="form-control" required></div><div class="form-group"><label for="service-edit-price">Harga per bulan</label><input id="service-edit-price" name="price" type="number" min="0" step="0.01" class="form-control" required></div><div class="form-group"><label for="service-edit-description">Deskripsi</label><textarea id="service-edit-description" name="description" class="form-control"></textarea></div><input type="hidden" name="is_active" value="0"><div class="custom-control custom-checkbox"><input id="service-edit-active" type="checkbox" class="custom-control-input"><label class="custom-control-label" for="service-edit-active">Aktif</label></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary">Simpan Perubahan</button></div></form></div></div></div>
<div class="modal fade" id="service-delete-modal" tabindex="-1" role="dialog" aria-labelledby="service-delete-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form id="service-delete-form" method="POST"><div class="modal-header"><h5 id="service-delete-title" class="modal-title">Hapus Layanan</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><div class="modal-body">@csrf @method('DELETE')<p>Hapus layanan <strong id="service-delete-name"></strong>?</p></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-danger">Hapus</button></div></form></div></div></div>
@push('styles')<link rel="stylesheet" href="{{ asset('bundles/datatables/datatables.min.css') }}">@endpush
@push('plugin-scripts')<script src="{{ asset('bundles/datatables/datatables.min.js') }}"></script>@endpush
@push('scripts')<script>$(function(){ $('#services-table').DataTable({pageLength:10,ordering:true,responsive:true}); $('.js-edit-service').on('click',function(){var b=$(this);$('#service-edit-form').attr('action','{{ url('/admin/services') }}/'+b.data('id'));$('#service-edit-name').val(b.data('name'));$('#service-edit-speed').val(b.data('speed'));$('#service-edit-price').val(b.data('price'));$('#service-edit-description').val(b.data('description'));$('#service-edit-active').prop('checked',String(b.data('active'))==='1').on('change',function(){$('#service-edit-form input[name=is_active]').val(this.checked?'1':'0');}).trigger('change');});$('.js-delete-service').on('click',function(){var b=$(this);$('#service-delete-form').attr('action','{{ url('/admin/services') }}/'+b.data('id'));$('#service-delete-name').text(b.data('name'));});@if($errors->any() && old('form')==='create')$('#service-create-modal').modal('show');@endif });</script>@endpush
@endsection
