@extends('layouts.app')

@section('title', 'Detail Perubahan Layanan')
@section('page-title', 'Detail Perubahan Layanan')
@section('breadcrumb', 'Detail Perubahan Layanan')

@section('content')
@error('upgrade')<div class="alert alert-danger">{{ $message }}</div>@enderror
<div class="row"><div class="col-12 col-lg-6"><div class="card"><div class="card-header"><h4>Data Customer</h4></div><div class="card-body"><dl class="row mb-0"><dt class="col-5">Nama</dt><dd class="col-7">{{ $upgrade->customer->user->name }}</dd><dt class="col-5">Nomor</dt><dd class="col-7">{{ $upgrade->customer->customer_number }}</dd><dt class="col-5">Layanan saat ini</dt><dd class="col-7">{{ $upgrade->fromService->name }}</dd><dt class="col-5">Layanan tujuan</dt><dd class="col-7">{{ $upgrade->toService->name }}</dd><dt class="col-5">Status</dt><dd class="col-7">{{ ucfirst($upgrade->status->value) }}</dd><dt class="col-5">Catatan</dt><dd class="col-7">{{ $upgrade->note ?: '-' }}</dd></dl></div></div></div><div class="col-12 col-lg-6"><div class="card"><div class="card-header"><h4>Keputusan</h4></div><div class="card-body">@if($upgrade->effective_period)<p>Periode efektif: <strong>{{ $upgrade->effective_period }}</strong></p>@endif@if($upgrade->reviewer)<p>Diproses oleh {{ $upgrade->reviewer->name }} pada {{ format_tanggal_id($upgrade->reviewed_at) }}.</p>@endif@if($upgrade->status->value === 'pending')<form method="POST" action="{{ route('admin.upgrades.approve', $upgrade) }}" class="mb-2">@csrf<button class="btn btn-success btn-block" onclick="return confirm('Setujui perubahan layanan ini?')"><i class="fas fa-check"></i> Setujui Perubahan</button></form><button class="btn btn-danger btn-block" data-toggle="modal" data-target="#reject-upgrade-modal"><i class="fas fa-times"></i> Tolak</button>@else<p class="text-muted">Pengajuan ini sudah diproses.</p>@endif</div></div></div></div>
<div class="modal fade" id="reject-upgrade-modal" tabindex="-1" role="dialog" aria-labelledby="reject-upgrade-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form method="POST" action="{{ route('admin.upgrades.reject', $upgrade) }}">@csrf<div class="modal-header"><h5 id="reject-upgrade-title" class="modal-title">Tolak Perubahan Layanan</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><div class="modal-body"><label for="rejection_reason">Alasan penolakan <span class="text-danger">*</span></label><textarea id="rejection_reason" name="rejection_reason" class="form-control @error('rejection_reason') is-invalid @enderror" rows="4" required>{{ old('rejection_reason') }}</textarea>@error('rejection_reason')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button class="btn btn-danger">Tolak Pengajuan</button></div></form></div></div></div>
@endsection
