@extends('layouts.app')

@section('title', 'Laporan Harian')
@section('page-title', 'Laporan Harian')
@section('breadcrumb', 'Laporan Harian')

@section('content')
@error('report_date')<div class="alert alert-danger">{{ $message }}</div>@enderror
<div class="card"><div class="card-header"><h4>Daftar Laporan</h4><div class="card-header-action"><button class="btn btn-primary" data-toggle="modal" data-target="#report-create-modal"><i class="fas fa-plus"></i> Buat &amp; Kirim</button></div></div><div class="card-body"><form method="GET" class="form-inline mb-3"><label for="status" class="mr-2">Status</label><select id="status" name="status" class="form-control mr-2"><option value="">Semua</option><option value="dikirim" @selected(request('status') === 'dikirim')>Dikirim</option><option value="revisi" @selected(request('status') === 'revisi')>Revisi</option><option value="diarsipkan" @selected(request('status') === 'diarsipkan')>Diarsipkan</option></select><label for="date" class="mr-2 ml-2">Tanggal</label><input id="date" name="date" type="date" value="{{ request('date') }}" class="form-control mr-2"><button class="btn btn-light">Filter</button></form><div class="table-responsive"><table id="admin-reports-table" class="table table-striped"><thead><tr><th>Tanggal</th><th>Sumber</th><th>Status</th><th>Confirmed</th><th>Ditolak</th><th>Pending</th><th>Aksi</th></tr></thead><tbody>@forelse($reports as $report)<tr><td>{{ format_tanggal_id($report->report_date) }}</td><td>{{ ucfirst($report->source) }}</td><td>{{ ucfirst($report->status->value) }}</td><td>{{ $report->total_confirmed_count }} / {{ format_rupiah($report->total_confirmed_amount) }}</td><td>{{ $report->rejected_count }}</td><td>{{ $report->pending_count }}</td><td><a class="btn btn-sm btn-primary" href="{{ route('admin.reports.show', $report) }}">Detail</a></td></tr>@empty<tr><td colspan="7" class="text-center text-muted">Belum ada laporan.</td></tr>@endforelse</tbody></table></div></div></div>
<div class="modal fade" id="report-create-modal" tabindex="-1" role="dialog" aria-labelledby="report-create-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form method="POST" action="{{ route('admin.reports.store') }}">@csrf<div class="modal-header"><h5 id="report-create-title" class="modal-title">Buat &amp; Kirim Laporan</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><div class="modal-body"><div class="form-group"><label for="report_date">Tanggal laporan</label><input id="report_date" name="report_date" type="date" value="{{ old('report_date', today()->toDateString()) }}" class="form-control @error('report_date') is-invalid @enderror" required>@error('report_date')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button class="btn btn-primary">Buat &amp; Kirim</button></div></form></div></div></div>
@endsection
@push('styles')<link rel="stylesheet" href="{{ asset('bundles/datatables/datatables.min.css') }}">@endpush
@push('plugin-scripts')<script src="{{ asset('bundles/datatables/datatables.min.js') }}"></script>@endpush
@push('scripts')<script>$(function(){ $('#admin-reports-table').DataTable({pageLength:10,ordering:true,responsive:true}); });</script>@endpush
