@extends('layouts.app')

@section('title', 'Detail Laporan Harian')
@section('page-title', 'Detail Laporan Harian')
@section('breadcrumb', 'Detail Laporan')

@section('content')
@php($statusClass = ['dikirim' => 'warning', 'revisi' => 'danger', 'diarsipkan' => 'success'][$report->status->value] ?? 'secondary')
<div class="card"><div class="card-header"><h4>Laporan {{ format_tanggal_id($report->report_date) }}</h4><div class="card-header-action"><span class="badge badge-{{ $statusClass }}">{{ ucfirst($report->status->value) }}</span></div></div><div class="card-body"><div class="row"><div class="col-md-3"><div class="card card-statistic-1"><div class="card-icon bg-success"><i class="fas fa-check"></i></div><div class="card-wrap"><div class="card-header"><h4>Confirmed</h4></div><div class="card-body">{{ $report->total_confirmed_count }}</div><small class="d-block px-3 pb-2">{{ format_rupiah($report->total_confirmed_amount) }}</small></div></div></div><div class="col-md-3"><div class="card card-statistic-1"><div class="card-icon bg-danger"><i class="fas fa-times"></i></div><div class="card-wrap"><div class="card-header"><h4>Ditolak</h4></div><div class="card-body">{{ $report->rejected_count }}</div></div></div></div><div class="col-md-3"><div class="card card-statistic-1"><div class="card-icon bg-warning"><i class="fas fa-clock"></i></div><div class="card-wrap"><div class="card-header"><h4>Pending</h4></div><div class="card-body">{{ $report->pending_count }}</div></div></div></div><div class="col-md-3"><dl><dt>Sumber</dt><dd>{{ ucfirst($report->source) }}</dd><dt>Dikirim</dt><dd>{{ format_tanggal_id($report->sent_at) }}</dd></dl></div></div>@if($report->revision_note)<div class="alert alert-warning"><strong>Catatan revisi:</strong> {{ $report->revision_note }}@if($report->reviewer) <br><small>Oleh {{ $report->reviewer->name }}</small>@endif</div>@endif</div></div>
<div class="card"><div class="card-header"><h4>Daftar Transaksi</h4></div><div class="card-body"><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Tanggal</th><th>Customer</th><th>Tagihan</th><th>Jumlah</th><th>Status</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ format_tanggal_id($payment->verified_at ?: $payment->paid_date) }}</td><td>{{ $payment->bill->customer->user->name }}</td><td>{{ $payment->bill->bill_number }}</td><td>{{ format_rupiah($payment->amount) }}</td><td>{{ ucfirst($payment->status->value) }}</td></tr>@empty<tr><td colspan="5" class="text-center text-muted">Tidak ada transaksi pada tanggal laporan.</td></tr>@endforelse</tbody></table></div></div></div>
@if($report->status->value === 'revisi')<form method="POST" action="{{ route('admin.reports.resend', $report) }}">@csrf<button class="btn btn-primary"><i class="fas fa-paper-plane"></i> Perbaiki &amp; Kirim Ulang</button></form>@endif
@endsection
