@extends('layouts.app')

@section('title', 'Layanan Saya')
@section('page-title', 'Layanan Saya')
@section('breadcrumb', 'Layanan Saya')

@section('content')
<div class="row"><div class="col-12 col-lg-5"><div class="card card-primary"><div class="card-header"><h4>Layanan Aktif</h4></div><div class="card-body"><h5>{{ $customer->service->name }}</h5><p class="mb-1">Kecepatan: {{ $customer->service->speed_mbps }} Mbps</p><p class="mb-0">Harga: <strong>{{ format_rupiah($customer->service->price) }}</strong> / bulan</p></div></div>@if($pending)<div class="alert alert-info"><i class="fas fa-clock"></i> Pengajuan upgrade ke <strong>{{ $pending->toService->name }}</strong> sedang menunggu keputusan admin.</div>@elseif($lastRequest && $lastRequest->status->value === 'approved')<div class="alert alert-success"><i class="fas fa-calendar-alt"></i> Dijadwalkan ke layanan <strong>{{ $lastRequest->toService->name }}</strong> mulai periode <strong>{{ $lastRequest->effective_period }}</strong>.</div>@elseif($lastRequest && $lastRequest->status->value === 'applied')<div class="alert alert-success"><i class="fas fa-check"></i> Upgrade terakhir ke {{ $lastRequest->toService->name }} sudah diterapkan.</div>@endif</div><div class="col-12 col-lg-7"><div class="card"><div class="card-header"><h4>Ajukan Upgrade</h4></div><div class="card-body">@if($pending)<p class="text-muted">Selesaikan pengajuan yang sedang menunggu sebelum mengajukan upgrade baru.</p>@elseif($services->isEmpty())<div class="empty-state"><div class="empty-state-icon"><i class="fas fa-box"></i></div><h2>Belum ada pilihan upgrade</h2><p class="lead">Saat ini belum tersedia layanan aktif lain.</p></div>@else<form method="POST" action="{{ route('customer.services.upgrades.store') }}">@csrf<div class="form-group"><label for="to_service_id">Layanan tujuan</label><select id="to_service_id" name="to_service_id" class="form-control @error('to_service_id') is-invalid @enderror" required><option value="">Pilih layanan</option>@foreach($services as $service)<option value="{{ $service->id }}" @selected(old('to_service_id') === $service->id)>{{ $service->name }} - {{ $service->speed_mbps }} Mbps ({{ format_rupiah($service->price) }})</option>@endforeach</select>@error('to_service_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="form-group"><label for="note">Catatan <span class="text-muted">(opsional)</span></label><textarea id="note" name="note" rows="3" class="form-control @error('note') is-invalid @enderror">{{ old('note') }}</textarea>@error('note')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><button class="btn btn-primary"><i class="fas fa-paper-plane"></i> Ajukan Upgrade</button></form>@endif</div></div></div></div>
<div class="card"><div class="card-header"><h4>Status Pengajuan Terakhir</h4></div><div class="card-body">@if($lastRequest)<dl class="row mb-0"><dt class="col-sm-4">Dari</dt><dd class="col-sm-8">{{ $lastRequest->fromService->name }}</dd><dt class="col-sm-4">Ke</dt><dd class="col-sm-8">{{ $lastRequest->toService->name }}</dd><dt class="col-sm-4">Status</dt><dd class="col-sm-8">{{ ucfirst($lastRequest->status->value) }}</dd>@if($lastRequest->effective_period)<dt class="col-sm-4">Periode efektif</dt><dd class="col-sm-8">{{ $lastRequest->effective_period }}</dd>@endif
@if($lastRequest->note)<dt class="col-sm-4">Catatan</dt><dd class="col-sm-8">{{ $lastRequest->note }}</dd>@endif</dl>@else<p class="text-muted mb-0">Belum ada pengajuan upgrade.</p>@endif</div></div>
@endsection
