@extends('layouts.app')

@section('title', 'Daftar Tagihan')
@section('page-title', $isAdmin ? 'Daftar Tagihan' : 'Pemantauan Tagihan')
@section('breadcrumb', 'Tagihan')

@section('content')
<div class="card"><div class="card-header"><h4>{{ $isAdmin ? 'Daftar Tagihan' : 'Pemantauan Tagihan' }}</h4>@if($isAdmin)<div class="card-header-action"><button class="btn btn-primary" data-toggle="modal" data-target="#generate-bills-modal"><i class="fas fa-sync"></i> Generate Manual</button></div>@endif</div><div class="card-body">
    <form method="GET" class="mb-4"><div class="form-row"><div class="form-group col-md-3"><label for="period">Periode</label><input id="period" name="period" type="month" class="form-control" value="{{ request('period') }}"></div><div class="form-group col-md-3"><label for="status">Status</label><select id="status" name="status" class="form-control"><option value="">Semua status</option>@foreach(['belum_bayar' => 'Belum Bayar', 'menunggu_verifikasi' => 'Menunggu Verifikasi', 'lunas' => 'Lunas', 'terlambat' => 'Terlambat'] as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></div><div class="form-group col-md-4"><label for="q">Cari nomor tagihan/customer</label><input id="q" name="q" class="form-control" value="{{ request('q') }}" placeholder="INV-... atau nama customer"></div><div class="form-group col-md-2 d-flex align-items-end"><button class="btn btn-primary mr-2" type="submit">Filter</button><a href="{{ $isAdmin ? route('admin.bills.index') : route('supervisor.bills.index') }}" class="btn btn-light">Reset</a></div></div></form>
    <div class="table-responsive"><table id="bills-table" class="table table-striped"><thead><tr><th>Nomor</th><th>Customer</th><th>Periode</th><th>Layanan</th><th>Jumlah</th><th>Jatuh Tempo</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($bills as $bill)<tr><td>{{ $bill->bill_number }}</td><td>{{ $bill->customer->user->name }}<small class="d-block text-muted">{{ $bill->customer->customer_number }}</small></td><td>{{ $bill->period }}</td><td>{{ $bill->service->name }}</td><td>{{ format_rupiah($bill->amount) }}</td><td>{{ format_tanggal_id($bill->due_date) }}</td><td><span class="badge badge-{{ ['belum_bayar'=>'warning','menunggu_verifikasi'=>'info','lunas'=>'success','terlambat'=>'danger'][$bill->status->value] ?? 'secondary' }}">{{ ['belum_bayar'=>'Belum Bayar','menunggu_verifikasi'=>'Menunggu Verifikasi','lunas'=>'Lunas','terlambat'=>'Terlambat'][$bill->status->value] ?? $bill->status->value }}</span></td><td><a class="btn btn-sm btn-primary" href="{{ $isAdmin ? route('admin.bills.show', $bill) : route('supervisor.bills.show', $bill) }}"><i class="fas fa-eye"></i> Detail</a></td></tr>@empty<tr><td colspan="8" class="text-center text-muted">Belum ada tagihan sesuai filter.</td></tr>@endforelse</tbody></table></div>
</div></div>
@if($isAdmin)<div class="modal fade" id="generate-bills-modal" tabindex="-1" role="dialog" aria-labelledby="generate-bills-title" aria-hidden="true"><div class="modal-dialog" role="document"><div class="modal-content"><form method="POST" action="{{ route('admin.bills.generate') }}"><div class="modal-header"><h5 id="generate-bills-title" class="modal-title">Generate Tagihan Manual</h5><button type="button" class="close" data-dismiss="modal" aria-label="Tutup"><span aria-hidden="true">&times;</span></button></div><div class="modal-body">@csrf<div class="form-group"><label for="generate-period">Periode tagihan</label><input id="generate-period" name="period" type="month" class="form-control" value="{{ old('period', now()->format('Y-m')) }}" required><small class="form-text text-muted">Customer aktif akan dibuatkan satu tagihan untuk periode ini.</small></div></div><div class="modal-footer"><button type="button" class="btn btn-light" data-dismiss="modal">Batal</button><button type="submit" class="btn btn-primary">Generate</button></div></form></div></div></div>@endif
@push('styles')<link rel="stylesheet" href="{{ asset('bundles/datatables/datatables.min.css') }}">@endpush
@push('plugin-scripts')<script src="{{ asset('bundles/datatables/datatables.min.js') }}"></script>@endpush
@push('scripts')<script>$(function(){ $('#bills-table').DataTable({pageLength:10,ordering:true,responsive:true}); });</script>@endpush
@endsection
