@extends('layouts.app')

@section('title', 'Riwayat Pembayaran')
@section('page-title', 'Riwayat Pembayaran')
@section('breadcrumb', 'Riwayat Pembayaran')

@section('content')
<div class="card"><div class="card-header"><h4>Riwayat Tagihan</h4></div><div class="card-body"><div class="table-responsive"><table class="table table-striped"><thead><tr><th>Nomor</th><th>Periode</th><th>Jumlah</th><th>Status</th><th>Aksi</th></tr></thead><tbody>@forelse($bills as $bill)<tr><td>{{ $bill->bill_number }}</td><td>{{ $bill->period }}</td><td>{{ format_rupiah($bill->amount) }}</td><td>{{ ucfirst(str_replace('_', ' ', $bill->status->value)) }}</td><td><a class="btn btn-sm btn-primary" href="{{ route('customer.bills.show', $bill) }}">Detail</a></td></tr>@empty<tr><td colspan="5" class="text-center text-muted">Belum ada riwayat tagihan.</td></tr>@endforelse</tbody></table></div></div></div><div class="card"><div class="card-header"><h4>Riwayat Pembayaran</h4></div><div class="card-body"><div class="table-responsive"><table id="customer-payments-table" class="table table-striped"><thead><tr><th>Tanggal</th><th>Tagihan</th><th>Metode</th><th>Jumlah</th><th>Status</th><th>Alasan penolakan</th><th>Bukti</th><th>Kuitansi</th></tr></thead><tbody>@forelse($payments as $payment)<tr><td>{{ format_tanggal_id($payment->paid_date) }}</td><td>{{ $payment->bill->bill_number }}</td><td>{{ $payment->paymentMethod->name }}</td><td>{{ format_rupiah($payment->amount) }}</td><td><span class="badge badge-{{ ['pending'=>'warning','confirmed'=>'success','rejected'=>'danger'][$payment->status->value] ?? 'secondary' }}">{{ ucfirst($payment->status->value) }}</span></td><td>{{ $payment->rejection_reason ?: '-' }}</td><td><a href="{{ route('customer.payments.proof', $payment) }}" target="_blank" rel="noopener" class="btn btn-sm btn-light">Lihat bukti</a></td><td>@if($payment->receipt)<a href="{{ route('customer.receipts.show', $payment->receipt) }}" target="_blank" rel="noopener" class="btn btn-sm btn-success">E-receipt</a>@else - @endif</td></tr>@empty<tr><td colspan="8" class="text-center text-muted"><i class="fas fa-history fa-2x d-block mb-2"></i>Belum ada pembayaran.</td></tr>@endforelse</tbody></table></div></div></div>
@push('styles')<link rel="stylesheet" href="{{ asset('bundles/datatables/datatables.min.css') }}">@endpush
@push('plugin-scripts')<script src="{{ asset('bundles/datatables/datatables.min.js') }}"></script>@endpush
@push('scripts')<script>$(function(){ $('#customer-payments-table').DataTable({pageLength:10,ordering:true,responsive:true,language:{emptyTable:'Belum ada pembayaran.',search:'Cari:',lengthMenu:'Tampilkan _MENU_',info:'Menampilkan _START_ sampai _END_ dari _TOTAL_ pembayaran',paginate:{next:'Berikutnya',previous:'Sebelumnya'}}}); });</script>@endpush
@endsection
